<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="tests\mock-assembly.dll" total="8" errors="1" failures="1" not-run="7" ignored="4" skipped="0" invalid="3" date="2008-11-22" time="20:17:48">
  <environment nunit-version="2.5.0.8327" clr-version="2.0.50727.1433" os-version="Microsoft Windows NT 5.1.2600 Service Pack 2" platform="Win32NT" cwd="C:\Program Files\NUnit 2.5\bin\net-2.0" machine-name="FERRARI" user="Charlie" user-domain="FERRARI" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite name="tests\mock-assembly.dll" executed="True" success="False" time="0.125" asserts="0">
    <results>
      <test-suite name="NUnit" executed="True" success="False" time="0.109" asserts="0">
        <results>
          <test-suite name="Tests" executed="True" success="False" time="0.109" asserts="0">
            <results>
              <test-suite name="Assemblies" executed="True" success="False" time="0.109" asserts="0">
                <results>
                  <test-suite name="MockTestFixture" description="Fake Test Fixture" executed="True" success="False" time="0.109" asserts="0">
                    <categories>
                      <category name="FixtureCategory" />
                    </categories>
                    <results>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.FailingTest" executed="True" success="False" time="0.047" asserts="0">
                        <failure>
                          <message><![CDATA[Intentional failure]]></message>
                          <stack-trace><![CDATA[at NUnit.Tests.Assemblies.MockTestFixture.FailingTest()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.MockTest1" description="Mock Test #1" executed="True" success="True" time="0.000" asserts="0" />
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.MockTest2" executed="True" success="True" time="0.000" asserts="0">
                        <categories>
                          <category name="MockCategory" />
                        </categories>
                        <properties>
                          <property name="Severity" value="Critical" />
                        </properties>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.MockTest3" executed="True" success="True" time="0.000" asserts="0">
                        <categories>
                          <category name="AnotherCategory" />
                          <category name="MockCategory" />
                        </categories>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.MockTest4" executed="False">
                        <categories>
                          <category name="Foo" />
                        </categories>
                        <reason>
                          <message><![CDATA[ignoring this test method for now]]></message>
                        </reason>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.MockTest5" executed="False">
                        <reason>
                          <message><![CDATA[Method is not public]]></message>
                        </reason>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest" executed="False">
                        <reason>
                          <message><![CDATA[No arguments provided]]></message>
                        </reason>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.TestWithException" executed="True" success="False" time="0.000" asserts="0">
                        <failure>
                          <message><![CDATA[System.ApplicationException : Intentional Exception]]></message>
                          <stack-trace><![CDATA[at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException()
at NUnit.Tests.Assemblies.MockTestFixture.TestWithException()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="NUnit.Tests.Assemblies.MockTestFixture.TestWithManyProperties" executed="True" success="True" time="0.000" asserts="0">
                        <properties>
                          <property name="Size" value="5" />
                          <property name="TargetMethod" value="SomeClassName" />
                        </properties>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite name="BadFixture" executed="False">
                <reason>
                  <message><![CDATA[No suitable constructor was found]]></message>
                </reason>
                <results>
                  <test-case name="NUnit.Tests.BadFixture.SomeTest" executed="False">
                    <reason>
                      <message><![CDATA[No suitable constructor was found]]></message>
                    </reason>
                  </test-case>
                </results>
              </test-suite>
              <test-suite name="IgnoredFixture" executed="False">
                <reason>
                  <message><![CDATA[]]></message>
                </reason>
                <results>
                  <test-case name="NUnit.Tests.IgnoredFixture.Test1" executed="False">
                    <reason>
                      <message><![CDATA[]]></message>
                    </reason>
                  </test-case>
                  <test-case name="NUnit.Tests.IgnoredFixture.Test2" executed="False">
                    <reason>
                      <message><![CDATA[]]></message>
                    </reason>
                  </test-case>
                  <test-case name="NUnit.Tests.IgnoredFixture.Test3" executed="False">
                    <reason>
                      <message><![CDATA[]]></message>
                    </reason>
                  </test-case>
                </results>
              </test-suite>
              <test-suite name="Singletons" executed="True" success="True" time="0.000" asserts="0">
                <results>
                  <test-suite name="OneTestCase" executed="True" success="True" time="0.000" asserts="0">
                    <results>
                      <test-case name="NUnit.Tests.Singletons.OneTestCase.TestCase" executed="True" success="True" time="0.000" asserts="0" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite name="TestAssembly" executed="True" success="True" time="0.000" asserts="0">
                <results>
                  <test-suite name="MockTestFixture" executed="True" success="True" time="0.000" asserts="0">
                    <results>
                      <test-case name="NUnit.Tests.TestAssembly.MockTestFixture.MyTest" executed="True" success="True" time="0.000" asserts="0" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>